import { Container } from '@chakra-ui/react';
import { MongoClient } from 'mongodb';
import Head from 'next/head';
import MeetupList from '../components/meetup/MeetupList';
import Navbar from '../components/navbar';

const DUMMY_MEETUPS = [
  {
    id: '1',
    title: 'First',
    image:
      'https://images.pexels.com/photos/3155666/pexels-photo-3155666.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    description: 'Description',
  },
  {
    id: '2',
    title: 'Second',
    image:
      'https://images.pexels.com/photos/3155666/pexels-photo-3155666.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    description: 'Description',
  },
];

export default function Home(props) {
  return (
    <>
      <Navbar />
      <Container maxW='container.sm'>
        <Head>
          <title>Create Next App</title>
          <meta name='description' content='Generated by create next app' />
          <link rel='icon' href='/favicon.ico' />
        </Head>
        <MeetupList meetups={props.meetups} />
      </Container>
    </>
  );
}

// export async function getServerSideProps(context) {
//   const req = context.req;
//   const res = context.res;

//   fetch data from API

//   return { props: { meetups: DUMMY_MEETUPS } };
// }

export async function getStaticProps() {
  // fetch data from api
  const client = await MongoClient.connect(
    'mongodb+srv://user-nineria:tUh1mj8hmOQLAM1N@cluster0.y5ii0.mongodb.net/meetups?retryWrites=true&w=majority'
  );

  const db = client.db();
  const meetupsCollection = db.collection('meetups');

  const meetups = await meetupsCollection.find().toArray();

  client.close();

  return {
    props: {
      meetups: meetups.map((meetup) => ({
        id: meetup._id.toString(),
        title: meetup.title,
        image: meetup.image,
        description: meetup.description,
      })),
    },
    revalidate: 3,
  };
}
