import { Container } from '@chakra-ui/react';
import Head from 'next/head';
import { useEffect, useState } from 'react';
import MeetupList from '../components/meetup/MeetupList';
import Navbar from '../components/navbar';

const DUMMY_MEETUPS = [
  {
    id: '1',
    title: 'First',
    image:
      'https://images.pexels.com/photos/3155666/pexels-photo-3155666.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    description: 'Description',
  },
  {
    id: '2',
    title: 'Second',
    image:
      'https://images.pexels.com/photos/3155666/pexels-photo-3155666.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    description: 'Description',
  },
];

export default function Home(props) {
  return (
    <>
      <Navbar />
      <Container maxW='container.sm'>
        <Head>
          <title>Create Next App</title>
          <meta name='description' content='Generated by create next app' />
          <link rel='icon' href='/favicon.ico' />
        </Head>
        <MeetupList meetups={props.meetups} />
      </Container>
    </>
  );
}

export async function getStaticProps() {
  return {
    props: { meetups: DUMMY_MEETUPS },
  };
}
